// source: command.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.auctioncmd.AuctionResponse');
goog.provide('proto.auctioncmd.AuctionResponse.ResponseCase');
goog.provide('proto.auctioncmd.AuctionResponse.ResponseType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.auctioncmd.GetPlayerInfoResponse');
goog.require('proto.auctioncmd.UpdatePlayerInfoResponse');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.auctioncmd.AuctionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.auctioncmd.AuctionResponse.oneofGroups_);
};
goog.inherits(proto.auctioncmd.AuctionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.auctioncmd.AuctionResponse.displayName = 'proto.auctioncmd.AuctionResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.auctioncmd.AuctionResponse.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.auctioncmd.AuctionResponse.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  GET_PLAYER_INFO_RESPONSE: 3,
  UPDATE_PLAYER_INFO_RESPONSE: 4
};

/**
 * @return {proto.auctioncmd.AuctionResponse.ResponseCase}
 */
proto.auctioncmd.AuctionResponse.prototype.getResponseCase = function() {
  return /** @type {proto.auctioncmd.AuctionResponse.ResponseCase} */(jspb.Message.computeOneofCase(this, proto.auctioncmd.AuctionResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.auctioncmd.AuctionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.auctioncmd.AuctionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.auctioncmd.AuctionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.auctioncmd.AuctionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    errormsg: jspb.Message.getFieldWithDefault(msg, 1, ""),
    responseType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    getPlayerInfoResponse: (f = msg.getGetPlayerInfoResponse()) && proto.auctioncmd.GetPlayerInfoResponse.toObject(includeInstance, f),
    updatePlayerInfoResponse: (f = msg.getUpdatePlayerInfoResponse()) && proto.auctioncmd.UpdatePlayerInfoResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.auctioncmd.AuctionResponse}
 */
proto.auctioncmd.AuctionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.auctioncmd.AuctionResponse;
  return proto.auctioncmd.AuctionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.auctioncmd.AuctionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.auctioncmd.AuctionResponse}
 */
proto.auctioncmd.AuctionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormsg(value);
      break;
    case 2:
      var value = /** @type {!proto.auctioncmd.AuctionResponse.ResponseType} */ (reader.readEnum());
      msg.setResponseType(value);
      break;
    case 3:
      var value = new proto.auctioncmd.GetPlayerInfoResponse;
      reader.readMessage(value,proto.auctioncmd.GetPlayerInfoResponse.deserializeBinaryFromReader);
      msg.setGetPlayerInfoResponse(value);
      break;
    case 4:
      var value = new proto.auctioncmd.UpdatePlayerInfoResponse;
      reader.readMessage(value,proto.auctioncmd.UpdatePlayerInfoResponse.deserializeBinaryFromReader);
      msg.setUpdatePlayerInfoResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.auctioncmd.AuctionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.auctioncmd.AuctionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.auctioncmd.AuctionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.auctioncmd.AuctionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrormsg();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getResponseType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getGetPlayerInfoResponse();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.auctioncmd.GetPlayerInfoResponse.serializeBinaryToWriter
    );
  }
  f = message.getUpdatePlayerInfoResponse();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.auctioncmd.UpdatePlayerInfoResponse.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.auctioncmd.AuctionResponse.ResponseType = {
  ERROR: 0,
  GET_PLAYER_INFO: 1,
  UPDATE_PLAYER_INFO: 2
};

/**
 * optional string errormsg = 1;
 * @return {string}
 */
proto.auctioncmd.AuctionResponse.prototype.getErrormsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.auctioncmd.AuctionResponse} returns this
 */
proto.auctioncmd.AuctionResponse.prototype.setErrormsg = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ResponseType response_type = 2;
 * @return {!proto.auctioncmd.AuctionResponse.ResponseType}
 */
proto.auctioncmd.AuctionResponse.prototype.getResponseType = function() {
  return /** @type {!proto.auctioncmd.AuctionResponse.ResponseType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.auctioncmd.AuctionResponse.ResponseType} value
 * @return {!proto.auctioncmd.AuctionResponse} returns this
 */
proto.auctioncmd.AuctionResponse.prototype.setResponseType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional GetPlayerInfoResponse get_player_info_response = 3;
 * @return {?proto.auctioncmd.GetPlayerInfoResponse}
 */
proto.auctioncmd.AuctionResponse.prototype.getGetPlayerInfoResponse = function() {
  return /** @type{?proto.auctioncmd.GetPlayerInfoResponse} */ (
    jspb.Message.getWrapperField(this, proto.auctioncmd.GetPlayerInfoResponse, 3));
};


/**
 * @param {?proto.auctioncmd.GetPlayerInfoResponse|undefined} value
 * @return {!proto.auctioncmd.AuctionResponse} returns this
*/
proto.auctioncmd.AuctionResponse.prototype.setGetPlayerInfoResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.auctioncmd.AuctionResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.auctioncmd.AuctionResponse} returns this
 */
proto.auctioncmd.AuctionResponse.prototype.clearGetPlayerInfoResponse = function() {
  return this.setGetPlayerInfoResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.auctioncmd.AuctionResponse.prototype.hasGetPlayerInfoResponse = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional UpdatePlayerInfoResponse update_player_info_response = 4;
 * @return {?proto.auctioncmd.UpdatePlayerInfoResponse}
 */
proto.auctioncmd.AuctionResponse.prototype.getUpdatePlayerInfoResponse = function() {
  return /** @type{?proto.auctioncmd.UpdatePlayerInfoResponse} */ (
    jspb.Message.getWrapperField(this, proto.auctioncmd.UpdatePlayerInfoResponse, 4));
};


/**
 * @param {?proto.auctioncmd.UpdatePlayerInfoResponse|undefined} value
 * @return {!proto.auctioncmd.AuctionResponse} returns this
*/
proto.auctioncmd.AuctionResponse.prototype.setUpdatePlayerInfoResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.auctioncmd.AuctionResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.auctioncmd.AuctionResponse} returns this
 */
proto.auctioncmd.AuctionResponse.prototype.clearUpdatePlayerInfoResponse = function() {
  return this.setUpdatePlayerInfoResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.auctioncmd.AuctionResponse.prototype.hasUpdatePlayerInfoResponse = function() {
  return jspb.Message.getField(this, 4) != null;
};


