// source: command.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.auctioncmd.AuctionCommand');
goog.provide('proto.auctioncmd.AuctionCommand.CmdType');
goog.provide('proto.auctioncmd.AuctionCommand.CommandCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.auctioncmd.GetPlayerInfoCommand');
goog.require('proto.auctioncmd.UpdatePlayerInfoCommand');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.auctioncmd.AuctionCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.auctioncmd.AuctionCommand.oneofGroups_);
};
goog.inherits(proto.auctioncmd.AuctionCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.auctioncmd.AuctionCommand.displayName = 'proto.auctioncmd.AuctionCommand';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.auctioncmd.AuctionCommand.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.auctioncmd.AuctionCommand.CommandCase = {
  COMMAND_NOT_SET: 0,
  GET_PLAYER_INFO_CMD: 2,
  UPDATE_PLAYER_INFO_CMD: 3
};

/**
 * @return {proto.auctioncmd.AuctionCommand.CommandCase}
 */
proto.auctioncmd.AuctionCommand.prototype.getCommandCase = function() {
  return /** @type {proto.auctioncmd.AuctionCommand.CommandCase} */(jspb.Message.computeOneofCase(this, proto.auctioncmd.AuctionCommand.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.auctioncmd.AuctionCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.auctioncmd.AuctionCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.auctioncmd.AuctionCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.auctioncmd.AuctionCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    cmdType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    getPlayerInfoCmd: (f = msg.getGetPlayerInfoCmd()) && proto.auctioncmd.GetPlayerInfoCommand.toObject(includeInstance, f),
    updatePlayerInfoCmd: (f = msg.getUpdatePlayerInfoCmd()) && proto.auctioncmd.UpdatePlayerInfoCommand.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.auctioncmd.AuctionCommand}
 */
proto.auctioncmd.AuctionCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.auctioncmd.AuctionCommand;
  return proto.auctioncmd.AuctionCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.auctioncmd.AuctionCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.auctioncmd.AuctionCommand}
 */
proto.auctioncmd.AuctionCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.auctioncmd.AuctionCommand.CmdType} */ (reader.readEnum());
      msg.setCmdType(value);
      break;
    case 2:
      var value = new proto.auctioncmd.GetPlayerInfoCommand;
      reader.readMessage(value,proto.auctioncmd.GetPlayerInfoCommand.deserializeBinaryFromReader);
      msg.setGetPlayerInfoCmd(value);
      break;
    case 3:
      var value = new proto.auctioncmd.UpdatePlayerInfoCommand;
      reader.readMessage(value,proto.auctioncmd.UpdatePlayerInfoCommand.deserializeBinaryFromReader);
      msg.setUpdatePlayerInfoCmd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.auctioncmd.AuctionCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.auctioncmd.AuctionCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.auctioncmd.AuctionCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.auctioncmd.AuctionCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCmdType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getGetPlayerInfoCmd();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.auctioncmd.GetPlayerInfoCommand.serializeBinaryToWriter
    );
  }
  f = message.getUpdatePlayerInfoCmd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.auctioncmd.UpdatePlayerInfoCommand.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.auctioncmd.AuctionCommand.CmdType = {
  NONE: 0,
  GET_PLAYER_INFO: 1,
  UPDATE_PLAYER_INFO: 2
};

/**
 * optional CmdType cmd_type = 1;
 * @return {!proto.auctioncmd.AuctionCommand.CmdType}
 */
proto.auctioncmd.AuctionCommand.prototype.getCmdType = function() {
  return /** @type {!proto.auctioncmd.AuctionCommand.CmdType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.auctioncmd.AuctionCommand.CmdType} value
 * @return {!proto.auctioncmd.AuctionCommand} returns this
 */
proto.auctioncmd.AuctionCommand.prototype.setCmdType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional GetPlayerInfoCommand get_player_info_cmd = 2;
 * @return {?proto.auctioncmd.GetPlayerInfoCommand}
 */
proto.auctioncmd.AuctionCommand.prototype.getGetPlayerInfoCmd = function() {
  return /** @type{?proto.auctioncmd.GetPlayerInfoCommand} */ (
    jspb.Message.getWrapperField(this, proto.auctioncmd.GetPlayerInfoCommand, 2));
};


/**
 * @param {?proto.auctioncmd.GetPlayerInfoCommand|undefined} value
 * @return {!proto.auctioncmd.AuctionCommand} returns this
*/
proto.auctioncmd.AuctionCommand.prototype.setGetPlayerInfoCmd = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.auctioncmd.AuctionCommand.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.auctioncmd.AuctionCommand} returns this
 */
proto.auctioncmd.AuctionCommand.prototype.clearGetPlayerInfoCmd = function() {
  return this.setGetPlayerInfoCmd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.auctioncmd.AuctionCommand.prototype.hasGetPlayerInfoCmd = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional UpdatePlayerInfoCommand update_player_info_cmd = 3;
 * @return {?proto.auctioncmd.UpdatePlayerInfoCommand}
 */
proto.auctioncmd.AuctionCommand.prototype.getUpdatePlayerInfoCmd = function() {
  return /** @type{?proto.auctioncmd.UpdatePlayerInfoCommand} */ (
    jspb.Message.getWrapperField(this, proto.auctioncmd.UpdatePlayerInfoCommand, 3));
};


/**
 * @param {?proto.auctioncmd.UpdatePlayerInfoCommand|undefined} value
 * @return {!proto.auctioncmd.AuctionCommand} returns this
*/
proto.auctioncmd.AuctionCommand.prototype.setUpdatePlayerInfoCmd = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.auctioncmd.AuctionCommand.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.auctioncmd.AuctionCommand} returns this
 */
proto.auctioncmd.AuctionCommand.prototype.clearUpdatePlayerInfoCmd = function() {
  return this.setUpdatePlayerInfoCmd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.auctioncmd.AuctionCommand.prototype.hasUpdatePlayerInfoCmd = function() {
  return jspb.Message.getField(this, 3) != null;
};


