// source: command.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.auctioncmd.GetPlayerInfoResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.auctioncmd.PlayerType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.auctioncmd.GetPlayerInfoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.auctioncmd.GetPlayerInfoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.auctioncmd.GetPlayerInfoResponse.displayName = 'proto.auctioncmd.GetPlayerInfoResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.auctioncmd.GetPlayerInfoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.auctioncmd.GetPlayerInfoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.auctioncmd.GetPlayerInfoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    playerBio: jspb.Message.getFieldWithDefault(msg, 2, ""),
    playerProfileLink: jspb.Message.getFieldWithDefault(msg, 3, ""),
    playerType: jspb.Message.getFieldWithDefault(msg, 4, 0),
    playerPicture: msg.getPlayerPicture_asB64(),
    isPlayerActive: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.auctioncmd.GetPlayerInfoResponse}
 */
proto.auctioncmd.GetPlayerInfoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.auctioncmd.GetPlayerInfoResponse;
  return proto.auctioncmd.GetPlayerInfoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.auctioncmd.GetPlayerInfoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.auctioncmd.GetPlayerInfoResponse}
 */
proto.auctioncmd.GetPlayerInfoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerBio(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerProfileLink(value);
      break;
    case 4:
      var value = /** @type {!proto.auctioncmd.PlayerType} */ (reader.readEnum());
      msg.setPlayerType(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPlayerPicture(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPlayerActive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.auctioncmd.GetPlayerInfoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.auctioncmd.GetPlayerInfoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.auctioncmd.GetPlayerInfoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPlayerBio();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPlayerProfileLink();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPlayerType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getPlayerPicture_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getIsPlayerActive();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional string player_name = 1;
 * @return {string}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.getPlayerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.auctioncmd.GetPlayerInfoResponse} returns this
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.setPlayerName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string player_bio = 2;
 * @return {string}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.getPlayerBio = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.auctioncmd.GetPlayerInfoResponse} returns this
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.setPlayerBio = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string player_profile_link = 3;
 * @return {string}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.getPlayerProfileLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.auctioncmd.GetPlayerInfoResponse} returns this
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.setPlayerProfileLink = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional PlayerType player_type = 4;
 * @return {!proto.auctioncmd.PlayerType}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.getPlayerType = function() {
  return /** @type {!proto.auctioncmd.PlayerType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.auctioncmd.PlayerType} value
 * @return {!proto.auctioncmd.GetPlayerInfoResponse} returns this
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.setPlayerType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional bytes player_picture = 5;
 * @return {string}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.getPlayerPicture = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes player_picture = 5;
 * This is a type-conversion wrapper around `getPlayerPicture()`
 * @return {string}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.getPlayerPicture_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPlayerPicture()));
};


/**
 * optional bytes player_picture = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPlayerPicture()`
 * @return {!Uint8Array}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.getPlayerPicture_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPlayerPicture()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.auctioncmd.GetPlayerInfoResponse} returns this
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.setPlayerPicture = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional bool is_player_active = 6;
 * @return {boolean}
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.getIsPlayerActive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.auctioncmd.GetPlayerInfoResponse} returns this
 */
proto.auctioncmd.GetPlayerInfoResponse.prototype.setIsPlayerActive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


